[features]
seeds = false
[programs.localnet]
solana_extractor = "BbM5Yg3eqXrxTCVcQBRvb13zyDPKCq9WqujmBJNosf5w"

[programs.devnet]
solana_extractor = "BbM5Yg3eqXrxTCVcQBRvb13zyDPKCq9WqujmBJNosf5w"

[programs.mainnet]
solana_extractor = "BbM5Yg3eqXrxTCVcQBRvb13zyDPKCq9WqujmBJNosf5w"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "/home/rasitha/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
copy-idl = "mkdir -p app/src/idl && cp target/idl/solana_extractor.json app/src/idl/solana_extractor.json"
